// <auto-generated />
using System;
using FALOFinancialProofing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FALOFinancialProofing.Migrations
{
    [DbContext(typeof(FALOFinancialProofingDbContext))]
    partial class FALOFinancialProofingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FALOFinancialProofing.Models.AccountingBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("AccountingBooks");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.ApproveProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproveNumber")
                        .HasColumnType("int");

                    b.Property<string>("ApproveStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestId");

                    b.ToTable("ApproveProcesses");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.AttachmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("AttachmentFiles");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankCodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CassoAccountID")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("acqId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("CassoAccountID")
                        .IsUnique();

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "1016161976",
                            BankCodeName = "VietComBank",
                            CassoAccountID = 123L,
                            OwnerName = "Nguyen Van Duc",
                            acqId = 970436
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "4270774590",
                            BankCodeName = "BIDV",
                            CassoAccountID = 222L,
                            OwnerName = "Bui Minh Manh",
                            acqId = 970418
                        });
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FundTarget")
                        .HasColumnType("bigint");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdateLog")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CreateBy");

                    b.HasIndex("ProjectId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CampaignMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<decimal>("Debt")
                        .HasColumnType("money");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("CampaignMembers");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CampaignRequestApproveHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CampaignRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfApproval")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("CampaignRequestId");

                    b.ToTable("CampaignRequestApproveHistories");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateCampaignFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("CreateCampaignFiles");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateCampaignRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("CreateCampaignRequests");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateProjectFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("CreateProjectFiles");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateProjectRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("CreateProjectRequests");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateProjectRequestApproveHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreateProjectRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfApproval")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("CreateProjectRequestId");

                    b.ToTable("CreateProjectRequestApproveHistories");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateQrCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreateQrCodes");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.MoveNextCampaignStatusRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusOfCampaign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignID");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("MoveNextCampaignStatusRequests");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.MoveNextCampaignStatusRequestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfApproval")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("MoveNextCampaignStatusRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MoveNextCampaignStatusRequestId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("MoveNextCampaignStatusRequestHistories");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainActivity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Main_office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolunteerExperience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolunteerObjectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.OrganizationMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationMember");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.RequestForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExpectedMoney")
                        .HasColumnType("float");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TypeId");

                    b.ToTable("RequestForms");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "Pre-Pay"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "Payment"
                        });
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "205d4496-4ac8-40d9-84b9-e09e1ada7a49",
                            ConcurrencyStamp = "acccef8b-20f3-4de0-8ee9-5a3690f094ed",
                            Name = "Project Manager",
                            NormalizedName = "PROJECT MANAGER"
                        },
                        new
                        {
                            Id = "4e7b2c09-e0b0-4ddd-9694-ebf3e21e2472",
                            ConcurrencyStamp = "1a777fbf-24db-4247-bd76-db376d703ea9",
                            Name = "Volunteer Leader",
                            NormalizedName = "VOLUNTEER LEADER"
                        },
                        new
                        {
                            Id = "83292e2c-6c86-4153-bdc5-760d05ec2293",
                            ConcurrencyStamp = "606fea67-ae89-4b3f-ac93-ccceda6fc85f",
                            Name = "Accounting",
                            NormalizedName = "ACCOUNTING"
                        },
                        new
                        {
                            Id = "83292e2c-6c86-4153-bdc5-760d05ec2295",
                            ConcurrencyStamp = "606fea67-ae89-4b3f-ac93-ccceda6fc85g",
                            Name = "Volunteer",
                            NormalizedName = "VOLUNTEER"
                        },
                        new
                        {
                            Id = "83292e2c-6c86-4153-bdc5-760d05ec2299",
                            ConcurrencyStamp = "606fea67-ae89-4b3f-ac93-ccceda6fc85h",
                            Name = "Project Management Board",
                            NormalizedName = "PROJECT MANAGEMENT BOARD"
                        },
                        new
                        {
                            Id = "15db7f37-5dbc-4035-9b00-a0af4c3fe8bb",
                            ConcurrencyStamp = "ba58588f-f626-41a0-8fca-b74481367335",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "15db7f37-5dbc-4035-9b00-a0af4c3fe8bd",
                            ConcurrencyStamp = "ba58588f-f626-41a0-8fca-b74481367337",
                            Name = "Donor",
                            NormalizedName = "DONOR"
                        });
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.SDG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SDGName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SDGs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SDGName = "No Poverty"
                        },
                        new
                        {
                            Id = 2,
                            SDGName = "Zero Hunger"
                        },
                        new
                        {
                            Id = 3,
                            SDGName = "Good Health And Well-Being"
                        },
                        new
                        {
                            Id = 4,
                            SDGName = "Quality Education"
                        },
                        new
                        {
                            Id = 5,
                            SDGName = "Gender Equality"
                        },
                        new
                        {
                            Id = 6,
                            SDGName = "Clean Water And Sanitation"
                        });
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SocialNetworksLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SocialNetworks");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.TransactionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<long?>("CassoTransactionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CreateQrCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("tid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CassoTransactionId")
                        .IsUnique()
                        .HasFilter("[CassoTransactionId] IS NOT NULL");

                    b.HasIndex("CreateQrCodeId");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VolunteerExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolunteerGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPlace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-1234-567890abcdef",
                            AccessFailedCount = 0,
                            Address = "123 Đường Chính, Thành phố A",
                            Bio = "Lập trình viên phần mềm đam mê công nghệ web.",
                            BirthDate = new DateOnly(1990, 5, 15),
                            ConcurrencyStamp = "dbe4e9d1-be15-42ea-914d-dc7ed1237e63",
                            Education = "Đại học Bách Khoa, Khoa Công nghệ Thông tin",
                            Email = "admin@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Nguyễn",
                            Gender = true,
                            Hobby = "Đi bộ đường dài, Nhiếp ảnh",
                            LastName = "Văn An",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FALOFINANCIAL.COM",
                            NormalizedUserName = "ADMIN@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da2b19ae-f42f-491b-b370-e67f25d16f21",
                            Skill = "C#, .NET, JavaScript",
                            Strength = "Giải quyết vấn đề, Làm việc nhóm",
                            TwoFactorEnabled = false,
                            UserName = "admin@falofinancial.com",
                            VolunteerExperience = "Tình nguyện viên tại Mái ấm Tình Thương",
                            VolunteerGoal = "Đóng góp cho sự phát triển cộng đồng địa phương.",
                            WorkPlace = "Công ty ABC"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f678-9012-3456-7890abcdef1",
                            AccessFailedCount = 0,
                            Address = "456 Đường Số 2, Thành phố B",
                            Bio = "Nhân viên văn phòng năng động.",
                            BirthDate = new DateOnly(1988, 7, 20),
                            ConcurrencyStamp = "5c3a7381-7b9c-41b5-ab6c-fbb67f2550ca",
                            Education = "Cao đẳng Kinh tế, Quản trị văn phòng",
                            Email = "user1@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Lê",
                            Gender = false,
                            Hobby = "Xem phim, Nghe nhạc",
                            LastName = "Thị Bình",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER1@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8afa6bed-641d-41ef-8f52-5ad51b2df57e",
                            Skill = "Soạn thảo văn bản, Quản lý hồ sơ, Giao tiếp tốt",
                            Strength = "Cẩn thận, Chu đáo",
                            TwoFactorEnabled = false,
                            UserName = "user1@falofinancial.com",
                            VolunteerGoal = "Tham gia các hoạt động thiện nguyện giúp đỡ cộng đồng.",
                            WorkPlace = "Công ty XYZ"
                        },
                        new
                        {
                            Id = "c3d4e5f6-7890-1234-5678-90abcdef12",
                            AccessFailedCount = 0,
                            Address = "789 Đường 30/4, Thành phố CT",
                            Bio = "Lập trình viên tự do, thích khám phá công nghệ mới.",
                            BirthDate = new DateOnly(1995, 3, 10),
                            ConcurrencyStamp = "d1764107-dda4-4540-912e-aac030b105ae",
                            Education = "Đại học Cần Thơ, Công nghệ Phần mềm",
                            Email = "user2@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Cao",
                            Gender = true,
                            Hobby = "Đọc sách, Chơi thể thao",
                            LastName = "Văn Tuấn",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER2@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0dab950b-c548-42af-9913-10edc18ca4ab",
                            Skill = "PHP, MySQL, Laravel",
                            Strength = "Tự học, Sáng tạo",
                            TwoFactorEnabled = false,
                            UserName = "user2@falofinancial.com",
                            VolunteerExperience = "Tham gia dự án mã nguồn mở",
                            VolunteerGoal = "Đóng góp cho cộng đồng lập trình viên.",
                            WorkPlace = "Freelancer"
                        },
                        new
                        {
                            Id = "d4e5f678-9012-3456-7890-abcdef123",
                            AccessFailedCount = 0,
                            Address = "1011 Đường Lê Lợi, Quận 1, TP.HCM",
                            Bio = "Thích tham gia các hoạt động xã hội.",
                            BirthDate = new DateOnly(1992, 9, 25),
                            ConcurrencyStamp = "1e853b2b-e5f5-4072-a7f9-4d86d42b1701",
                            Education = "Đại học Kinh tế TP.HCM, Tài chính Ngân hàng",
                            Email = "user3@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Trần",
                            Gender = false,
                            Hobby = "Du lịch, Đọc sách",
                            LastName = "Thị Diễm",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER3@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b83d9399-5810-4201-9440-b8d86bf12a46",
                            Skill = "Phân tích tài chính, Tư vấn đầu tư",
                            Strength = "Giao tiếp, Thuyết trình",
                            TwoFactorEnabled = false,
                            UserName = "user3@falofinancial.com",
                            VolunteerExperience = "Tình nguyện viên dạy học cho trẻ em nghèo",
                            VolunteerGoal = "Góp phần xây dựng một xã hội tốt đẹp hơn.",
                            WorkPlace = "Ngân hàng ACB"
                        },
                        new
                        {
                            Id = "e5f67890-1234-5678-90ab-cdef12345",
                            AccessFailedCount = 0,
                            Address = "222 Đường Nguyễn Huệ, Quận 3, TP.HCM",
                            Bio = "Kỹ sư cầu nối, yêu thích công việc và cuộc sống.",
                            BirthDate = new DateOnly(1985, 12, 5),
                            ConcurrencyStamp = "3ef90099-510e-4556-affa-3b52baefe71d",
                            Education = "Đại học Giao thông Vận tải, Kỹ thuật Cầu đường",
                            Email = "user4@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Phạm",
                            Gender = true,
                            Hobby = "Chơi game, Xem phim",
                            LastName = "Văn Hoàng",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER4@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "84cd4b0b-eb54-43d4-89e0-e133d885530d",
                            Skill = "Thiết kế cầu đường, Quản lý dự án",
                            Strength = "Chịu khó, Ham học hỏi",
                            TwoFactorEnabled = false,
                            UserName = "user4@falofinancial.com",
                            VolunteerExperience = "Tham gia xây dựng cầu dân sinh",
                            VolunteerGoal = "Mang lại niềm vui cho mọi người.",
                            WorkPlace = "Công ty FPT"
                        },
                        new
                        {
                            Id = "f6789012-3456-7890-abcd-ef1234567",
                            AccessFailedCount = 0,
                            Address = "333 Đường Pasteur, Quận 1, TP.HCM",
                            Bio = "Y tá tận tâm với nghề.",
                            BirthDate = new DateOnly(1998, 6, 18),
                            ConcurrencyStamp = "6f951b75-368f-4d63-aa75-34c2a43e30c8",
                            Education = "Đại học Y Dược TP.HCM, Điều dưỡng",
                            Email = "user5@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Hồ",
                            Gender = false,
                            Hobby = "Nấu ăn, Làm bánh",
                            LastName = "Thị Mai",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER5@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3bf3f2d0-4e6a-401d-b7d3-679d6c0b9e36",
                            Skill = "Chăm sóc bệnh nhân, Sơ cứu",
                            Strength = "Kiên nhẫn, Yêu thương con người",
                            TwoFactorEnabled = false,
                            UserName = "user5@falofinancial.com",
                            VolunteerExperience = "Tình nguyện viên tại trạm y tế xã",
                            VolunteerGoal = "Giúp đỡ những người bệnh tật.",
                            WorkPlace = "Bệnh viện Chợ Rẫy"
                        },
                        new
                        {
                            Id = "78901234-5678-90ab-cdef-123456789",
                            AccessFailedCount = 0,
                            Address = "444 Đường Cách Mạng Tháng 8, Quận 10, TP.HCM",
                            Bio = "Giáo viên yêu nghề, mong muốn truyền đạt kiến thức cho học sinh.",
                            BirthDate = new DateOnly(1987, 4, 8),
                            ConcurrencyStamp = "fc9b59a3-9d1f-4882-8af8-5621abc7e4da",
                            Education = "Đại học Sư phạm TP.HCM, Ngữ văn",
                            Email = "user6@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Võ",
                            Gender = true,
                            Hobby = "Đọc sách, Du lịch",
                            LastName = "Văn Nam",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER6@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER6@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aadba03d-b144-4cda-bda0-ca7361089881",
                            Skill = "Giảng dạy, Truyền đạt kiến thức",
                            Strength = "Nhiệt tình, Trách nhiệm",
                            TwoFactorEnabled = false,
                            UserName = "user6@falofinancial.com",
                            VolunteerExperience = "Tham gia dạy học tình thương",
                            VolunteerGoal = "Cống hiến cho sự nghiệp giáo dục.",
                            WorkPlace = "Trường THPT Lê Hồng Phong"
                        },
                        new
                        {
                            Id = "89012345-6789-abcd-ef12-345678901",
                            AccessFailedCount = 0,
                            Address = "555 Đường Nguyễn Thị Minh Khai, Quận 3, TP.HCM",
                            Bio = "Nhà thiết kế thời trang, yêu cái đẹp và sự sáng tạo.",
                            BirthDate = new DateOnly(1994, 11, 12),
                            ConcurrencyStamp = "a02e5b93-183f-4753-998f-1df9c4f50acb",
                            Education = "Đại học Mỹ thuật TP.HCM, Thiết kế Thời trang",
                            Email = "user7@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Đỗ",
                            Gender = false,
                            Hobby = "Xem phim, Nghe nhạc",
                            LastName = "Thị Ngọc",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER7@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER7@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d525259b-01c3-4355-a556-68c9198360e8",
                            Skill = "Thiết kế, May vá",
                            Strength = "Sáng tạo, Thẩm mỹ",
                            TwoFactorEnabled = false,
                            UserName = "user7@falofinancial.com",
                            VolunteerExperience = "Tham gia thiết kế trang phục cho chương trình từ thiện",
                            VolunteerGoal = "Góp phần làm đẹp cho đời.",
                            WorkPlace = "Công ty Thiết kế Thời trang"
                        },
                        new
                        {
                            Id = "90123456-789a-bcde-f123-456789012",
                            AccessFailedCount = 0,
                            Address = "666 Đường Hai Bà Trưng, Quận 1, TP.HCM",
                            Bio = "Chuyên viên phân tích chứng khoán, đam mê thị trường tài chính.",
                            BirthDate = new DateOnly(1991, 8, 22),
                            ConcurrencyStamp = "e4c13025-1809-4bbc-8cc8-0fbeed1c5496",
                            Education = "Đại học Ngân hàng TP.HCM, Chứng khoán",
                            Email = "user8@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Lý",
                            Gender = true,
                            Hobby = "Chơi thể thao, Đọc sách",
                            LastName = "Văn Phong",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER8@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER8@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43380827-e1a6-4710-a229-c34f5f3ed721",
                            Skill = "Phân tích chứng khoán, Đầu tư",
                            Strength = "Tư duy logic, Phân tích",
                            TwoFactorEnabled = false,
                            UserName = "user8@falofinancial.com",
                            VolunteerExperience = "Tham gia tư vấn tài chính cho người dân",
                            VolunteerGoal = "Giúp mọi người hiểu rõ hơn về tài chính.",
                            WorkPlace = "Công ty Chứng khoán"
                        },
                        new
                        {
                            Id = "01234567-89ab-cdef-1234-567890123",
                            AccessFailedCount = 0,
                            Address = "777 Đường Điện Biên Phủ, Quận 3, TP.HCM",
                            Bio = "Luật sư, bảo vệ công lý và lẽ phải.",
                            BirthDate = new DateOnly(1993, 2, 14),
                            ConcurrencyStamp = "c6ef6602-b083-4d3c-a55b-fe80cedde872",
                            Education = "Đại học Luật TP.HCM, Luật",
                            Email = "user9@falofinancial.com",
                            EmailConfirmed = true,
                            FirstName = "Trương",
                            Gender = false,
                            Hobby = "Du lịch, Âm nhạc",
                            LastName = "Thị Thu",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER9@FALOFINANCIAL.COM",
                            NormalizedUserName = "USER9@FALOFINANCIAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAv5Ft/tuDcLhj/RXPpqHRsFhy0VLijVazfvQQVxP0kAk0apAye3AowK++jZi7YWYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc039a92-e9c2-4306-92a7-2b7bb12a2b3a",
                            Skill = "Tư vấn pháp lý, Soạn thảo văn bản pháp luật",
                            Strength = "Công bằng, Chính trực",
                            TwoFactorEnabled = false,
                            UserName = "user9@falofinancial.com",
                            VolunteerExperience = "Tư vấn pháp lý miễn phí cho người nghèo",
                            VolunteerGoal = "Đóng góp cho sự phát triển của pháp luật.",
                            WorkPlace = "Công ty Luật"
                        });
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a1b2c3d4-e5f6-7890-1234-567890abcdef",
                            RoleId = "15db7f37-5dbc-4035-9b00-a0af4c3fe8bb"
                        },
                        new
                        {
                            UserId = "b2c3d4e5-f678-9012-3456-7890abcdef1",
                            RoleId = "205d4496-4ac8-40d9-84b9-e09e1ada7a49"
                        },
                        new
                        {
                            UserId = "c3d4e5f6-7890-1234-5678-90abcdef12",
                            RoleId = "205d4496-4ac8-40d9-84b9-e09e1ada7a49"
                        },
                        new
                        {
                            UserId = "d4e5f678-9012-3456-7890-abcdef123",
                            RoleId = "83292e2c-6c86-4153-bdc5-760d05ec2299"
                        },
                        new
                        {
                            UserId = "e5f67890-1234-5678-90ab-cdef12345",
                            RoleId = "83292e2c-6c86-4153-bdc5-760d05ec2299"
                        },
                        new
                        {
                            UserId = "f6789012-3456-7890-abcd-ef1234567",
                            RoleId = "83292e2c-6c86-4153-bdc5-760d05ec2293"
                        },
                        new
                        {
                            UserId = "78901234-5678-90ab-cdef-123456789",
                            RoleId = "83292e2c-6c86-4153-bdc5-760d05ec2293"
                        },
                        new
                        {
                            UserId = "89012345-6789-abcd-ef12-345678901",
                            RoleId = "4e7b2c09-e0b0-4ddd-9694-ebf3e21e2472"
                        },
                        new
                        {
                            UserId = "90123456-789a-bcde-f123-456789012",
                            RoleId = "4e7b2c09-e0b0-4ddd-9694-ebf3e21e2472"
                        },
                        new
                        {
                            UserId = "01234567-89ab-cdef-1234-567890123",
                            RoleId = "83292e2c-6c86-4153-bdc5-760d05ec2295"
                        });
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.UserSDG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SDGId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SDGId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSDGs");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproveId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproveId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.AccountingBook", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Campaign", "Campaign")
                        .WithOne("AccountingBook")
                        .HasForeignKey("FALOFinancialProofing.Models.AccountingBook", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.ApproveProcess", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("ApproveProcesses")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.RequestForm", "RequestForm")
                        .WithMany("ApproveProcesses")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestForm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.AttachmentFile", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.RequestForm", "RequestForm")
                        .WithMany("AttachmentFiles")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestForm");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Campaign", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Bank", "Bank")
                        .WithMany("Campaigns")
                        .HasForeignKey("BankId");

                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.Project", "Project")
                        .WithMany("Campaigns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CampaignMember", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Campaign", "Campaign")
                        .WithMany("CampaignMembers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("CampaignMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CampaignRequestApproveHistory", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", "Approver")
                        .WithMany("CampaignRequestApproveHistories")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.CreateCampaignRequest", "CreateCampaignRequest")
                        .WithMany("CampaignRequestApproveHistories")
                        .HasForeignKey("CampaignRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("CreateCampaignRequest");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateCampaignFile", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.CreateCampaignRequest", "CampaignRequest")
                        .WithMany("CreateCampaignFiles")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignRequest");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateCampaignRequest", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Campaign", "Campaign")
                        .WithMany("CreateCampaignRequests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "ReceiverUser")
                        .WithMany("CreateCampaignRequestReceivers")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FALOFinancialProofing.Models.User", "SenderUser")
                        .WithMany("CreateCampaignRequestSenders")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateProjectFile", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.CreateProjectRequest", "ProjectRequest")
                        .WithMany("CreateProjectFiles")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateProjectRequest", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Project", "Project")
                        .WithMany("CreateProjectRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "ReceiverUser")
                        .WithMany("ReceiverCreateProjectRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FALOFinancialProofing.Models.User", "SenderUser")
                        .WithMany("SenderCreateProjectRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateProjectRequestApproveHistory", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", "Approver")
                        .WithMany("CreateProjectRequestApproveHistories")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.CreateProjectRequest", "CreateProjectRequest")
                        .WithMany("CreateProjectRequestApproveHistories")
                        .HasForeignKey("CreateProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("CreateProjectRequest");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateQrCode", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("CreateQrCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.MoveNextCampaignStatusRequest", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Campaign", "Campaign")
                        .WithMany("MoveNextCampaignStatusRequests")
                        .HasForeignKey("CampaignID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "ReceiverUser")
                        .WithMany("MoveNextCampaignStatusRequestReceiverUsers")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FALOFinancialProofing.Models.User", "SenderUser")
                        .WithMany("MoveNextCampaignStatusRequestSenderUsers")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.MoveNextCampaignStatusRequestHistory", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.MoveNextCampaignStatusRequest", "MoveNextCampaignStatusRequest")
                        .WithMany("MoveNextCampaignStatusRequestHistories")
                        .HasForeignKey("MoveNextCampaignStatusRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "Receiver")
                        .WithMany("MoveNextCampaignStatusRequestHistories")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoveNextCampaignStatusRequest");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.OrganizationMember", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Organization", "Organization")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Project", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.RequestForm", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Campaign", "Campaign")
                        .WithMany("RequestForms")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("RequestForms")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.RequestType", "RequestType")
                        .WithMany("RequestForms")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("RequestType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.SocialNetwork", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("SocialNetworks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.TransactionLog", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Campaign", "Campaign")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.CreateQrCode", "CreateQrCode")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("CreateQrCodeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Campaign");

                    b.Navigation("CreateQrCode");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.UserRole", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.UserSDG", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.SDG", "SDG")
                        .WithMany("UserSDGs")
                        .HasForeignKey("SDGId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FALOFinancialProofing.Models.User", "User")
                        .WithMany("UserSDGs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SDG");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Voucher", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.ApproveProcess", "ApproveProcess")
                        .WithMany("Vouchers")
                        .HasForeignKey("ApproveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproveProcess");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FALOFinancialProofing.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.ApproveProcess", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Bank", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Campaign", b =>
                {
                    b.Navigation("AccountingBook");

                    b.Navigation("CampaignMembers");

                    b.Navigation("CreateCampaignRequests");

                    b.Navigation("MoveNextCampaignStatusRequests");

                    b.Navigation("RequestForms");

                    b.Navigation("TransactionLogs");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateCampaignRequest", b =>
                {
                    b.Navigation("CampaignRequestApproveHistories");

                    b.Navigation("CreateCampaignFiles");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateProjectRequest", b =>
                {
                    b.Navigation("CreateProjectFiles");

                    b.Navigation("CreateProjectRequestApproveHistories");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.CreateQrCode", b =>
                {
                    b.Navigation("TransactionLogs");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.MoveNextCampaignStatusRequest", b =>
                {
                    b.Navigation("MoveNextCampaignStatusRequestHistories");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Organization", b =>
                {
                    b.Navigation("OrganizationMembers");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Project", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("CreateProjectRequests");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.RequestForm", b =>
                {
                    b.Navigation("ApproveProcesses");

                    b.Navigation("AttachmentFiles");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.RequestType", b =>
                {
                    b.Navigation("RequestForms");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.SDG", b =>
                {
                    b.Navigation("UserSDGs");
                });

            modelBuilder.Entity("FALOFinancialProofing.Models.User", b =>
                {
                    b.Navigation("ApproveProcesses");

                    b.Navigation("CampaignMembers");

                    b.Navigation("CampaignRequestApproveHistories");

                    b.Navigation("Campaigns");

                    b.Navigation("CreateCampaignRequestReceivers");

                    b.Navigation("CreateCampaignRequestSenders");

                    b.Navigation("CreateProjectRequestApproveHistories");

                    b.Navigation("CreateQrCodes");

                    b.Navigation("MoveNextCampaignStatusRequestHistories");

                    b.Navigation("MoveNextCampaignStatusRequestReceiverUsers");

                    b.Navigation("MoveNextCampaignStatusRequestSenderUsers");

                    b.Navigation("OrganizationMembers");

                    b.Navigation("Projects");

                    b.Navigation("ReceiverCreateProjectRequests");

                    b.Navigation("RequestForms");

                    b.Navigation("SenderCreateProjectRequests");

                    b.Navigation("SocialNetworks");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSDGs");
                });
#pragma warning restore 612, 618
        }
    }
}
